import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../../app/store";

export interface SearchState {
  searchTerm: string;
  history: string[];
  selectedPokemon?: number;
  selectedEvolution?: number;
}

const initialState: SearchState = {
  searchTerm: "",
  history: [],
};

export const searchSlice = createSlice({
  name: "search",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Use the PayloadAction type to declare the contents of `action.payload`
    addToHistory: (state, action: PayloadAction<string>) => {
      const newState = new Set([...state.history, action.payload]);
      state.history = [...newState];
    },
    setSearchTerm: (state, action: PayloadAction<string>) => {
      state.searchTerm = action.payload;
    },
    setSelectedPokemon: (state, action: PayloadAction<number | undefined>) => {
      state.selectedPokemon = action.payload;
    },
    setSelectedEvolution: (
      state,
      action: PayloadAction<number | undefined>
    ) => {
      state.selectedEvolution = action.payload;
    },
  },
  // // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {
  //   builder
  //     .addCase(searchAsync.pending, (state) => {
  //       state.status = "loading";
  //     })
  //     .addCase(searchAsync.fulfilled, (state, action) => {
  //       state.status = "idle";
  //       state.history.add(state.searchTerm || "");
  //     })
  //     .addCase(searchAsync.rejected, (state) => {
  //       state.status = "failed";
  //     });
  // },
});

export const { addToHistory, setSearchTerm, setSelectedPokemon } =
  searchSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.search.value)`
export const selectSearchTerm = (state: RootState) => state.search.searchTerm;
export const selectHistory = (state: RootState) => state.search.history;
export const selectPokemonDetail = (state: RootState) =>
  state.search.selectedPokemon;
export const selectedPokemonEvolution = (state: RootState) =>
  state.search.selectedEvolution;

export default searchSlice.reducer;
